### ISSUE TITLE
How does this interact with CSP?

### ISSUE THREAD

**Issue by otherdaniel** [mikewest/signature-based-sri#4]
Content Security Policy interacts with Subresource Integrity. For ed25519 signature, the extension of this interaction is probably straightforward, but.... should maybe still be specified.

**Comment by otherdaniel** [comment]
Well... last paragraph of "The Proposal" does describe this.
No longer sure there's something left to do, though. Please close if there's not much to add.

**Comment by devd** [comment]
Closing it out. I imagine there are other issues that we do need to discuss but we can file a new issue that is specific as needed.

**Comment by mikewest** [comment]
I think https://mikewest.github.io/signature-based-sri and https://w3c.github.io/webappsec-csp/#match-integrity-metadata-to-source-list now provide a pretty solid basis here. Closing this out.

**Comment by bakkot** [comment]
@mikewest Just to confirm my understanding, does this mean that you could have a CSP with `script-src 'ed25519-whatever'` and then a script with `<script integrity="ed25519-whatever" src="..."></script>` and the script would be allowed to execute (assuming it was served with the right headers)? And then you'd be able to update the script just by changing the server which provides the script to serve a new script with appropriate headers, without changing the CSP?

Because if so that would be _amazing_. Right now integrating with CSP when using dynamically generated scripts is a huge pain because you have to update the CSP every time, and that header is not necessarily controlled by the same team (or even the same company) as manages the contents of scripts. I think this would be worth calling out more explicitly in the readme, if so, because I think that for many web developers this will be the primary benefit. (E.g. I don't care about the `integrity` attribute at all, but simplifying CSP integration for dynamic scripts would be a godsend.) I'd be happy to send a PR noting this if you'd like.
